# Generated by Django 3.0.8 on 2020-07-22 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('menu_code', models.CharField(default='', max_length=100)),
                ('i_class_name', models.CharField(default='', max_length=100)),
                ('data_icon', models.CharField(default='', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('url', models.CharField(default='', max_length=128)),
                ('is_menu', models.IntegerField(default=1)),
                ('menu_code', models.CharField(default='', max_length=100)),
                ('i_class_name', models.CharField(default='', max_length=100)),
                ('data_icon', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=1, help_text='状态', verbose_name='状态')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('permissions', models.ManyToManyField(to='rbac.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', help_text='用户名', max_length=32, verbose_name='用户名')),
                ('password', models.CharField(default='123456', help_text='密码', max_length=64, verbose_name='密码')),
                ('nickname', models.CharField(default='', help_text='昵称', max_length=32, verbose_name='昵称')),
                ('email', models.EmailField(default='', help_text='邮箱', max_length=254, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('baomi', '保密')], default='male', max_length=6)),
                ('status', models.IntegerField(default=1, help_text='状态', verbose_name='状态')),
                ('is_superuser', models.IntegerField(default=0, help_text='是否是超级管理员', verbose_name='是否是超级管理员')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('lastlogintime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间')),
                ('roles', models.ManyToManyField(related_name='userrole', to='rbac.Role')),
            ],
        ),
    ]
